### ISSUE TITLE
There seems to be a problem with the lineNumbers code.

### ISSUE THREAD

**Issue by webgoto** [calumk/CodeCup#3]
Thank you for the great fork plugin.

I get an error and can't use the editor.

codecup@1.9.2

I wrote the following
```js
new codecup(editorEl, {language: 'js');
```
I got an error like this
```
Uncaught TypeError: Cannot set properties of undefined (setting 'innerHTML')
```
The code given in the reference was here.
```js
      updateLineNumbersCount() {
        let e = "";
        for (let t = 1; t <= this.lineNumber; t++)
          e += `<span class="codecup__lines__line">${t}</span>`;
>>      this.elLineNumbers.innerHTML = e
      }
```

### My thoughts
Even if the option lineNumbers is false, the problem may be occurring because `updateLineNumbersCount()` is executed.
https://github.com/calumk/codecup/blob/1ab71b4771fd0cdb25ad5e3eab7951177efd4841/src/codecup.js#L194

I think it would be good to fix it like this
```
this.updateLineNumbersCount();

↓

if (this.opts.lineNumbers) {
  this.updateLineNumbersCount();
}
```

**Comment by calumk** [comment]
Thanks for reporting. 
I have fixed with several changes in 

https://github.com/calumk/codecup/commit/73128489a761516acb2051311499eae2360d622b

https://github.com/calumk/codecup/commit/3a20a03624820d1cf1af0015098663bb343cb1ab

Please test. **1.9.4**

**Comment by webgoto** [comment]
I ran the new version and it worked fine. Thank you.
